# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0a4ca829228371e60c5906daefb34bad4699f5aff914385aae8502b434c9f8a36f41614252b787b27b6f6a4dfd67598a9eb7be3551bdc981c97e4ca42ccb49fe

test:
  secret_key_base: 8d24f2aafcb1fd72eb81794fabb2d3f2515a02c91da1ad77220f696805a55763c70ec49927b2ea9ebf932e6e0d1be2ae0203133bc13eb4ffc6564c72765a0696

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
